# remove temp preview bucket when the PR is merged/closed
name: Remove Temp Textile IPFS Bucket
on:
  pull_request:
    types: ['closed']

jobs:
  bucket_remove:
    name: Clean-up Temp Bucket
    env:
      BUCKET_NAME: 'blog-janaka-dev'
    runs-on: ubuntu-latest
    name: Remove a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bucket remove action
      id: push
      uses: textileio/github-action-bucket-remove@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}-${{ github.event.pull_request.id }}'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}