# create temp preview when PR is opened aginst master
# the bucket_remove action will delete the temp preview when the PR merged/closed.
name: Deploy Website on PR (IPFS Hosting)
on:
  pull_request:
    branches:
      - master
jobs:
  bucket_pull_request:
    name: Build & Deploy
    env:
      BUCKET_NAME: 'blog-janaka-dev'
    runs-on: ubuntu-latest
    name: Create a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build --prefix-paths # using ipfs plugin
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}-${{ github.event.pull_request.id }}'
        path: 'public/*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Get the Bucket URL
      run: echo "The Bucket URL is ${{ steps.push.outputs.url }}"